<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <Authors>Nozomu-san</Authors>
    <AssemblyTitle>Ped Voice Group Multiplayer</AssemblyTitle>
    <AssemblyVersion>10.09.2026.0</AssemblyVersion>
    <FileVersion>10.09.2026.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Source\" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Alloc8orStandardNatives">
      <HintPath>..\..\CommunityScriptHookVDotNetCore\Alloc8orStandardNatives\bin\x64\Release\net10.0\Alloc8orStandardNatives.dll</HintPath>
    </Reference>
    <Reference Include="CommunityScriptHookVDotNetCore">
      <HintPath>..\..\CommunityScriptHookVDotNetCore\CommunityScriptHookVDotNetCore\bin\x64\Release\net10.0\CommunityScriptHookVDotNetCore.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
